#1 use go.sum in docker build
Otherwise it will fail with:

```
0.895   github.com/cloudogu/ces-importer/configuration.test imports
0.895   github.com/stretchr/testify/require: missing go.sum entry for module providing package github.com/stretchr/testify/require (imported by github.com/cloudogu/ces-importer/configuration); to add:
0.895   go get -t github.com/cloudogu/ces-importer/configuration
------
Dockerfile:27
--------------------
  25 |
  26 |     # Build
  27 | >>> RUN go mod vendor
  28 |     RUN make compile-generic
  29 |
--------------------
ERROR: failed to solve: process "/bin/sh -c go mod vendor" did not complete successfully: exit code: 1
```